version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: increase
  assignees:
  - jonchang
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - jonchang
