name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to Github Docker
      run: echo -n $PACKAGE_ACCESS_TOKEN | docker login -u jonchang --password-stdin docker.pkg.github.com
      env:
        PACKAGE_ACCESS_TOKEN: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
    - name: Download data from the fishtreeoflife docker container
      run: scripts/docker.sh
    - name: Build fishtree R package documentation
      run: scripts/fishtree_docs.sh
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Update bundled packages
      run: gem install bundler && bundle update --bundler && bundle install
    - name: Build site
      run: rake
      env:
          JEKYLL_ENV: production
    - name: Test site
      run: scripts/test.sh
    - name: Deploy to Github pages
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_site
