name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download data from the fishtreeoflife docker container
      run: scripts/docker.sh
    - name: Build fishtree R package documentation
      run: scripts/fishtree_docs.sh
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Update bundled packages
      run: gem install bundler && bundle update --bundler && bundle install
    - name: Build site
      run: rake
    - name: Test site
      run: scripts/test.sh
