name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download data from the fishtreeoflife docker container
      run: scripts/docker.sh
    - name: Build fishtree R package documentation
      run: scripts/fishtree_docs.sh
    - name: Build the site in the jekyll/builder container
      container:
        image: jekyll/builder:latest
        volumes:
        - ${{ github.workspace }}:/srv/jekyll
        - ${{ github.workspace }}/_site:/srv/jekyll/_site
      run: |
        /bin/bash -c "chmod 777 srv/jekyll && bundle update --bundler && bundle install && rake && scripts/test.sh"
